# Bekerja dengan data numerik 

In [1]:
w1,w2,w3 = 0.3, 0.2,0.5

sebelum menjalankan sebuah program kita menentukan variabel yang  akan diambil

In [3]:
kanto_temp = 73
kanto_rainfall = 67
kanto_humidity = 43

variabel di atas dapat kita  gantikan ke dalam persamaan linear untuk memprediksi hasil apel di wilayah tersebut.

In [4]:
kanto_yield_apples = kanto_temp * w1 + kanto_rainfall * w2 + kanto_humidity * w3
kanto_yield_apples

56.8

In [5]:
print("The expected yield off the apple in kanto region is {} tons per hectare".format(kanto_yield_apples))

The expected yield off the apple in kanto region is 56.8 tons per hectare


Untuk mempermudah  perhitungan di atas untuk beberapa wilayah , kita dapat  merepresentasikan data iklim untuk setiap wilayah sebagai vektor yaitu daftar angka

In [6]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]


In [7]:
weights =[w1, w2, w3]

Selanjutnya menulis fungsi crop_yield(region, weights):
    untuk menghitung hasil apel  (tanaman lain) berdasarkan data iklim dan bobot masing-masing 

In [8]:
def crop_yield (region, weights):
    result = 0
    for x, w in zip(region, weights):
        result += x * w
    return result

In [9]:
crop_yield(kanto, weights)

56.8

In [10]:
crop_yield(johto, weights)

76.9

In [11]:
crop_yield(unova, weights)

74.9

# Beralih dari Python ke array Numpy

Library Numpy menyediakan fungsi bawaan untuk melakukan perkalian titik dari dua vektor. Namun, daftar tersebut harus terlebih dahulu diubah menjadi array numpy sebelum kita dapat melakukan operasi. Untuk memulai, mari impor numpymodul. Ini adalah praktik umum untuk mengimpor numpy dengan alias np.

In [12]:
import numpy as np

In [13]:
kanto = np.array([73, 67, 43])

In [14]:
kanto

array([73, 67, 43])

In [15]:
weights = np.array([w1,w2,w3])

In [16]:
weights

array([0.3, 0.2, 0.5])

In [17]:
type(kanto)

numpy.ndarray

In [18]:
type(weights)

numpy.ndarray

In [19]:
weights[0]

0.3

In [20]:
kanto[2]

43

# Beroperasi pada array Numpy

In [21]:
np.dot(kanto, weights)

56.8

Kita dapat mencapai hasil yang sama dengan operasi tingkat lebih rendah yang didukung oleh array Numpy: melakukan perkalian berdasarkan elemen dan menghitung jumlah angka yang dihasilkan.

In [22]:
(kanto * weights).sum()

56.8

In [23]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])


In [24]:
arr1 * arr2

array([ 4, 10, 18])

In [25]:
arr2.sum()

15

# Manfaat menggunakan array Numpy

Ada beberapa manfaat penting menggunakan array Numpy daripada daftar Python untuk beroperasi pada data numerik:

Kemudahan penggunaan : Anda dapat menulis ekspresi matematika yang kecil, ringkas, dan intuitif seperti (kanto * weights).sum()daripada menggunakan loop & fungsi khusus seperti crop_yeild.
Kinerja : Operasi dan fungsi numpy diimplementasikan secara internal di C ++, yang membuatnya jauh lebih cepat daripada menggunakan pernyataan & loop Python yang diinterpretasikan saat runtime


Berikut adalah perbandingan cepat perkalian titik yang dilakukan dari vektor dengan satu juta elemen yang masing-masing menggunakan loop Python vs. array Numpy.

In [26]:
# python list 
arr1 = list(range(1000000))
arr2 = list(range(1000000, 2000000))

# Numpy arrays
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [28]:
%%time 
result = 0
for x1, x2 in zip(arr1, arr2):
    result += x1* x2
result

Wall time: 559 ms


833332333333500000

In [29]:
%%time 
np.dot(arr1_np, arr2_np)

Wall time: 129 ms


-1942957984

Seperti yang Anda lihat, menggunakan np.dot100 kali lebih cepat daripada menggunakan forloop. Hal ini membuat Numpy sangat berguna saat bekerja dengan kumpulan data yang sangat besar dengan puluhan ribu atau jutaan titik data.

Mari selamatkan pekerjaan kita sebelum melanjutkan.

# Array Numpy multi -dimensi

In [31]:
climate_data = np.array([[73, 67, 63],
                  [91, 88, 64],
                  [87, 134, 58],
                  [102, 43, 37],
                  [69, 96, 70]])

In [32]:
climate_data

array([[ 73,  67,  63],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

Array numpy dapat memiliki sejumlah dimensi, dan panjang yang berbeda di setiap dimensi. Kita dapat memeriksa panjang setiap dimensi menggunakan .shapeproperti array

In [33]:
# 2D array matrix
climate_data.shape

(5, 3)

In [34]:
weights

array([0.3, 0.2, 0.5])

In [35]:
# 1D array(vector)
weights.shape

(3,)

In [36]:
# 3D array
arr3 = np.array([
    [[ 11, 12, 13],
     [ 13, 14, 15]],
    [[ 15, 16, 17],
    [17, 18, 19]]])

In [37]:
arr3.shape

(2, 2, 3)

Semua elemen dalam array numpy memiliki tipe data yang sama. Anda dapat memeriksa tipe data dari sebuah array menggunakan .dtype  properti

In [39]:
weights.dtype

dtype('float64')

In [41]:
climate_data.dtype

dtype('int32')

Jika sebuah array berisi bahkan satu angka floating point, semua elemen lainnya juga akan diubah menjadi float.

Kita bisa menggunakan np.matmulfungsi dari Numpy, atau cukup menggunakan @operator untuk melakukan perkalian matriks.

In [42]:
np.matmul(climate_data, weights)

array([66.8, 76.9, 81.9, 57.7, 74.9])

In [43]:
climate_data @ weights

array([66.8, 76.9, 81.9, 57.7, 74.9])

# Bekerja dengan data file csv

In [44]:
import urllib.request

urllib.request.urlretrieve(
    'https://hub.jovian.ml/wp-content/uploads/2020/08/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x25a0c2d1ca0>)

In [45]:
climate_data

array([[ 73,  67,  63],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [46]:
climate_data.shape

(5, 3)

Sekarang kita dapat menggunakan operator mulplikasi matriks @untuk memprediksi hasil apel untuk seluruh kumpulan data menggunakan kumpulan bobot tertentu.

In [47]:
weights = np.array([0.3, 0.2, 0.5])

In [48]:
yields = climate_data @ weights

In [49]:
yields

array([66.8, 76.9, 81.9, 57.7, 74.9])

In [50]:
yields.shape

(5,)

sekarang kita mendapatkan yields kembali ke climate data sebagai kolom keempat menggunakan np.concatenate fungsi tersebut.

In [57]:
climate_result = np.concatenate((climate_data, yields.reshape(5, 1)), axis = 1)

In [58]:
climate_result

array([[ 73. ,  67. ,  63. ,  66.8],
       [ 91. ,  88. ,  64. ,  76.9],
       [ 87. , 134. ,  58. ,  81.9],
       [102. ,  43. ,  37. ,  57.7],
       [ 69. ,  96. ,  70. ,  74.9]])